# Generated by Django 3.2.5 on 2021-09-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210914_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_author', models.CharField(max_length=50, verbose_name='İsim')),
                ('yorum_content', models.CharField(max_length=200, verbose_name='Yorum')),
                ('yorum_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='article.article', verbose_name='Makale')),
            ],
        ),
    ]
