# Generated by Django 3.2.5 on 2021-09-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_yorum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='yorum',
            options={'ordering': ['-yorum_date']},
        ),
    ]
